num = int(input('Informe um número de 0 a 9999: '))
print('Numero: {}'.format(num))
print('Unidade: {}'.format((num // 1 % 10)))
print('Dezena: {}'.format((num // 10 % 10)))
print('Centena: {}'.format((num // 100 % 10)))
print('Milhar: {}'.format((num // 1000 % 10)))